# version: '3.8'
# services:
#   mysqldb:
#     image: mysql:latest
#     environment:
#       - MYSQL_ROOT_PASSWORD=root
#       - MYSQL_DATABASE=userinfo
#     container_name: 'mysqldb'
#     healthcheck:
#       test: ["CMD", "mysqladmin", 'ping', '-h', 'localhost']
#       timeout: 20s
#       retries: 10
#     networks:
#        - my-network
      
#   mypythonapp:
#     build: ./
#     container_name: mypyapp 
#     volumes:
#       - ./service.txt:/myapp/service.txt
#     networks:
#       - my-network
#     depends_on:
#       mysqldb:
#          condition:service_healthy
#          std_open:true
#          tty:true
    

# networks:
#      my-network:



version: '3.8'
services:
  webapp_image:
    build: ./
    ports:
      - "8080:3000"
    container_name: 'mywebapp'
